

services:
  app:
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.5'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,staging
      - JAVA_OPTS=-Xms512m -Xmx1g

  sqlserver:
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          memory: 2g
          cpus: '1.0'

  redis:
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 256m
          cpus: '0.2'