
services:
  app:
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 2g
          cpus: '2.0'
        reservations:
          memory: 1g
          cpus: '1.0'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,prod
      - JAVA_OPTS=-Xms1g -Xmx2g -XX:+UseG1GC
    restart: unless-stopped

  sqlserver:
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '4.0'
        reservations:
          memory: 4g
          cpus: '2.0'
    restart: unless-stopped

  redis:
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.5'
    restart: unless-stopped