
services:
  app:
    volumes:
      - .:/app
      - /app/target
    ports:
      - "8080:8080"
      - "5005:5005"  
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005