# application-prod.yml - Production Configuration
spring:
  application:
    name: financeiro-api-simple
    
  # PostgreSQL Database
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
        
  sql:
    init:
      mode: never

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
    
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: false

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      
# Server Configuration
server:
  port: ${PORT:8080}
  compression:
    enabled: true
  error:
    include-stacktrace: never
    include-message: always

# Logging
logging:
  level:
    com.example.azure_sql_demo: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"