# application-docker.yml
spring:
  application:
    name: spring-boot-redis-app
  data:
    redis:
      host: redis-server
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 60000ms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics