spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 0
      maximum-pool-size: 3
      minimum-idle: 1
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server configuration
server:
  port: ${PORT:8080}

# Management endpoints (para health check)
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always

# Logging configuration  
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG