spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      validation-timeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 50
        order_inserts: true
        order_updates: true
      connection:
        provider_disables_autocommit: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        hbm2ddl:
          auto: create-drop

  sql:
    init:
      mode: never

  main:
    lazy-initialization: false

server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 20000
    keep-alive-timeout: 30000

debug: true

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.context: DEBUG
    org.springframework.beans: DEBUG
    org.hibernate: DEBUG
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
